version: '3.8'
services:
  javalin-fargate-template:
    image: dgandalcio/javalin-fargate-template:latest
    container_name: javalin-fargate-template
    hostname: docker-local
    env_file:
      - docker_config/otel_elastic_cloud.env
#      - docker_config/influxdb_service_event_cloud.env
#      - docker_config/otel_local.env
#      - docker_config/otel_nr.env
    environment:
      TZ: "UTC"
    ports:
      - "10001:10000"
    networks:
      - develop-bridge-network
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 512M

networks:
  develop-bridge-network:
    name: develop-bridge
    external: true