version: '3.8'
services:
  javalin-fargate-template:
    image: dgandalcio/javalin-fargate-template:latest
    container_name: javalin-fargate-template
    hostname: docker-local
    env_file:
      #      - docker_config/local_event_influxdb.env
      #      - docker_config/local_metric_influxdb.env
      #      - docker_config/local_log_log4j2.env
      #      - docker_config/local_trace_tempo.env
      - docker_config/otel_nr.env
    environment:
      TZ: "UTC"
    ports:
      - "10001:10000"
    networks:
      - develop-bridge-network
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G

networks:
  develop-bridge-network:
    name: develop-bridge
    external: true