version: '3.8'
services:
  javalin-fargate-template:
    image: javalin-fargate-template:latest
    container_name: javalin-fargate-template
    hostname: docker-local
    environment:
      TZ: "America/Chicago"
      SERVICE_EVENT_TYPE: "influxdb"
      SERVICE_EVENT_INFLUXDB_URL: "http://influxdb:8086"
      SERVICE_EVENT_INFLUXDB_TOKEN: "-s9vY1PF75mxFSadHLa-L6hDCmGu_K4h8zwGbR0lj-eGERgg8pSCjIYNQwTSezTyDSc9xIEAeZ4obUicfdmnSA=="
      OTEL_RESOURCE_ATTRIBUTES: "service.name=javalin-fargate-template,service.env=local,service.framework=javalin"
    ports:
      - "10001:10000"
    networks:
      - develop-bridge-network
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 512M

networks:
  develop-bridge-network:
    name: develop-bridge
    external: true