name: Push feature branch to ECR

on:
  push:
    branches-ignore:
      - main

jobs:
  push_to_ecr:
    name: Push to ECR
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Create local settings.xml file
        uses: s4u/maven-settings-action@v2.8.0
        with:
          servers: |
            [{
              "id": "396607284401.dkr.ecr.us-east-1.amazonaws.com",
              "username": "${{ secrets.AWS_ACCESS_KEY_ID }}",
              "password": "${{ secrets.AWS_SECRET_ACCESS_KEY }}"
            }]

      - name: Maven Install
        run: mvn clean install -P feature